### ISSUE TITLE
Hi This is Terada Dante🔥

### ISSUE THREAD

**Issue by TERADA-DANTE** [Tomoya-Sonok/Thinky#13]
__Greetings! Gentlemen🙌__
This is Terada, a.k.a Dante, from twitter.
As you guys may know, I am nominated as one of the collaborator in this project.
I gratefully take this with honor.
Thanks and Truly, Terada

**Comment by TERADA-DANTE** [comment]
@SomaSekimoto Hey. If you have seen this, Please close this issue.
Thanks and truly ❤

**Comment by SomaSekimoto** [comment]
Thank you our JS master😊

**Comment by TERADA-DANTE** [comment]
Me ain't JS master😀😀
